### ISSUE TITLE
Needn't require existing eclipse install

### ISSUE THREAD

**Issue by dnwe** [ferstl/eclipse-builder#1]
fyi, `eclipse-builder.sh` works nicely using the standalone headless p2 director which is available via the [Buckminster](http://www.eclipse.org/buckminster/downloads.html) project as [director_latest.zip](http://www.eclipse.org/downloads/download.php?file=/tools/buckminster/products/director_latest.zip)

It might worth updating the docs to mention this and/or adding a bit of bootstrap code to `eclipse-build.sh` to download and unzip it on the fly

**Comment by ferstl** [comment]
Thank you for the hint. The director uses the most recent P2 binaries and it works fine for building distributions for MacOS, Windows and Linux.
I will add it to the documentation. I don't want to add downloading/unzipping to the script (keep it simple) but it shouldn't be difficult to write a little wrapper around it to do the download/unzip.
