### ISSUE TITLE
eclipse-builder.sh return code success when provision failed?

### ISSUE THREAD

**Issue by dnwe** [ferstl/eclipse-builder#14]
I happened to notice that the most recent travis build [#1](https://travis-ci.org/ferstl/eclipse-builder/builds/175854347) was marked as successful, but actually the download.eclipse.org mirror that p2 director had chosen was down:
```
INFO: I/O exception (java.net.NoRouteToHostException) caught when connecting to
      {}->http://eclipse.c3sl.ufpr.br: No route to host
```

However, eclipse-builder.sh exited with a rc=0 and marked the build as successful. Do we have any mechanism for trapping errors like this from p2?

**Comment by ferstl** [comment]
I noticed this as well. This output comes as INFO from the P2 director. I supposed that the download finally worked and that the IUs could be installed.

When I made a distro locally and the download of an IU did not work, P2 aborted with an error.

**Comment by dnwe** [comment]
Ah so you think it did eventually succeed? I wonder if its worth adding a call to `ls -1 $PWD/eclipse-neon-linux-gtk-x86_64/features` to the end of the travis.yml just to output the list of features that were installed.

**Comment by ferstl** [comment]
I think the installation did succeed. Listing the `features` directory is a good idea to see if all the expected features are there.

**Comment by ferstl** [comment]
I added the listing but the problem didn't appear this time. I'll close this issue for now...
