### ISSUE TITLE
org.eclipse.epp.* packages fail to be found in mars updatesite

### ISSUE THREAD

**Issue by dnwe** [ferstl/eclipse-builder#3]
Using the included `01_eclipse-ide.conf` as-is seems to fails on a clean machine:

```
...
==> default: Installation failed.
==> default: The installable unit org.eclipse.epp.package.common.feature.feature.group has not been found. 
```

For some reason the `org.eclipse.epp.package.common.feature.feature.group` and `org.eclipse.epp.mpc.feature.group` installable units fail to be found.

This is strange, because doing a `-list` on the 4.5 updatesite clearly shows them as available:

```
 $ director -repository http://download.eclipse.org/releases/mars -list | grep -E 'org.eclipse.epp.mpc.feature.group|org.eclipse.epp.package.common.feature.feature.group' 
org.eclipse.epp.mpc.feature.group=1.4.0.v20150618-1659
org.eclipse.epp.package.common.feature.feature.group=4.5.0.20150621-1200
```

Any thoughts as to what might be causing this? Have you seen this yourself?

**Comment by dnwe** [comment]
(fyi, commenting out the epp packages does allow the install to proceed successfully)

**Comment by ferstl** [comment]
Oh, I accidentally deleted the [mars](http://download.eclipse.org/releases/mars) repository URL in 79a5923 .
