### ISSUE TITLE
Support for customizing eclipse.ini?

### ISSUE THREAD

**Issue by dnwe** [ferstl/eclipse-builder#6]
Obviously it is fairly trivial to do this yourself during a post-process part of the build, but I wonder if its something worth including in eclipse-builder.sh itself, so it is easily repeatable ?

For example, when building an eclipse containing the scala-ide plugins, it is basically a pre-requisite that you need to at least have the following minimum memory settings added to eclipse.ini:
-vmargs
-Xss8m
-Xms700m
-Xmx2048m

(feel free to close this off if you'd prefer to keep things simple)

**Comment by ferstl** [comment]
P2 does already have this kind of functionality called [Touchoints](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fp2_actions_touchpoints.html).

Basically, you can add a file called `p2.inf`, which contains instructions to modify `eclipse.ini` (and lots of other stuff), to one of your installable units. For your VM options, the `p2.inf` file would look like this:

```
instructions.configure=\
addJvmArg(jvmArg:-Xss8m);\
addJvmArg(jvmArg:-Xms700m);\
addJvmArg(jvmArg:-Xmx2048m);
```

For my eclipse distros I created a simple feature containing the `p2.inf` file with my settings. This feature can then be installed with the `eclipse-builder.sh`.

Off topic: are you sure about `-Xss8m`? Looks like a lot to me ;-)

**Comment by dnwe** [comment]
@ferstl aha excellent - I wasn't able to find anything with my attempts at Googling

RE: the 8 meg stack, that's just taken directly from the scala-ide faq [here](http://scala-ide.org/docs/current-user-doc/faq/index.html#I_am_running_out_of_stack_space_in_Eclipse___How_do_I_increase_the_stack_size_) - I'm totally guessing here, but I assume its something to do with internal eval of deeply recursive functions? _shrug_ :)

**Comment by ferstl** [comment]
@dnwe I created a little [example project](https://github.com/ferstl/eclipse-ini) containing my settings. You can just export it to an update site and install it with the install wizard or use it with the `eclipse-builder.sh`.
Note that the feature adds the VM settings to `eclipse.ini` not matter if they are already there.

**Comment by dnwe** [comment]
:+1: 
thanks
